# Language
language: node_js
node_js:
  - "node"
  - "iojs"


# Branches to build
branches:
  only:
    - master
    - develop

install:
  - cd "development"
  - npm install

# What to run
script:
  - tsc -p tsconfig-ci.json
  - cd "../automation"
  - python prepare_distribution_package.py
  - python create_local_package.py

# Notifications
notifications:
  email:
    recipients:
      - lee.winder@gmail.com
    on_success: change
    on_failure: change